name: MLflow CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 pandas numpy scikit-learn matplotlib seaborn

      - name: Run MLflow Project
        id: mlflow_run
        run: |
          mlflow run MLProject/ --env-manager local

      - name: Find Model Artifact
        id: find_model
        run: |
          MODEL_PATH=$(find mlruns -type d -name "model" | head -n 1)
          echo "MODEL_PATH=${MODEL_PATH}" >> $GITHUB_ENV
          echo "Ditemukan model di: ${MODEL_PATH}"

      - name: Upload MLflow Artifacts (Skilled)
        uses: actions/upload-artifact@v4
        with:
          name: mlruns-artifacts
          path: mlruns/

      - name: Copy Model for Docker Build
        run: |
          cp -r ${{ env.MODEL_PATH }} ./model

      - name: Log in to Docker Hub (Advance)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image (Advance)
        run: |
          docker build -t dnnuuyzzo/smsml-danuardi-saputro:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push dnnuuyzzo/smsml-danuardi-saputro:latest
